// Generated by gencpp from file tools_msgs/ConeInfo.msg
// DO NOT EDIT!


#ifndef TOOLS_MSGS_MESSAGE_CONEINFO_H
#define TOOLS_MSGS_MESSAGE_CONEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tools_msgs
{
template <class ContainerAllocator>
struct ConeInfo_
{
  typedef ConeInfo_<ContainerAllocator> Type;

  ConeInfo_()
    : cone_id(0)
    , color(0)
    , position_x(0.0)
    , position_y(0.0)
    , confidence(0.0)  {
    }
  ConeInfo_(const ContainerAllocator& _alloc)
    : cone_id(0)
    , color(0)
    , position_x(0.0)
    , position_y(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _cone_id_type;
  _cone_id_type cone_id;

   typedef int32_t _color_type;
  _color_type color;

   typedef float _position_x_type;
  _position_x_type position_x;

   typedef float _position_y_type;
  _position_y_type position_y;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::tools_msgs::ConeInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tools_msgs::ConeInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ConeInfo_

typedef ::tools_msgs::ConeInfo_<std::allocator<void> > ConeInfo;

typedef boost::shared_ptr< ::tools_msgs::ConeInfo > ConeInfoPtr;
typedef boost::shared_ptr< ::tools_msgs::ConeInfo const> ConeInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tools_msgs::ConeInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tools_msgs::ConeInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tools_msgs::ConeInfo_<ContainerAllocator1> & lhs, const ::tools_msgs::ConeInfo_<ContainerAllocator2> & rhs)
{
  return lhs.cone_id == rhs.cone_id &&
    lhs.color == rhs.color &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tools_msgs::ConeInfo_<ContainerAllocator1> & lhs, const ::tools_msgs::ConeInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tools_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tools_msgs::ConeInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tools_msgs::ConeInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_msgs::ConeInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_msgs::ConeInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_msgs::ConeInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_msgs::ConeInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tools_msgs::ConeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0da50e2dcec8ef7611d66b74becda81e";
  }

  static const char* value(const ::tools_msgs::ConeInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0da50e2dcec8ef76ULL;
  static const uint64_t static_value2 = 0x11d66b74becda81eULL;
};

template<class ContainerAllocator>
struct DataType< ::tools_msgs::ConeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tools_msgs/ConeInfo";
  }

  static const char* value(const ::tools_msgs::ConeInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tools_msgs::ConeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cone_id\n"
"int32 color\n"
"float32 position_x\n"
"float32 position_y\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::tools_msgs::ConeInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tools_msgs::ConeInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cone_id);
      stream.next(m.color);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tools_msgs::ConeInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tools_msgs::ConeInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cone_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position_x: ";
    Printer<float>::stream(s, indent + "  ", v.position_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position_y: ";
    Printer<float>::stream(s, indent + "  ", v.position_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOOLS_MSGS_MESSAGE_CONEINFO_H
