// Generated by gencpp from file tools_msgs/ConeArray.msg
// DO NOT EDIT!


#ifndef TOOLS_MSGS_MESSAGE_CONEARRAY_H
#define TOOLS_MSGS_MESSAGE_CONEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tools_msgs/ConeInfo.h>

namespace tools_msgs
{
template <class ContainerAllocator>
struct ConeArray_
{
  typedef ConeArray_<ContainerAllocator> Type;

  ConeArray_()
    : header()
    , cones()
    , count(0)  {
    }
  ConeArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cones(_alloc)
    , count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tools_msgs::ConeInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tools_msgs::ConeInfo_<ContainerAllocator> >> _cones_type;
  _cones_type cones;

   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::tools_msgs::ConeArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tools_msgs::ConeArray_<ContainerAllocator> const> ConstPtr;

}; // struct ConeArray_

typedef ::tools_msgs::ConeArray_<std::allocator<void> > ConeArray;

typedef boost::shared_ptr< ::tools_msgs::ConeArray > ConeArrayPtr;
typedef boost::shared_ptr< ::tools_msgs::ConeArray const> ConeArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tools_msgs::ConeArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tools_msgs::ConeArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tools_msgs::ConeArray_<ContainerAllocator1> & lhs, const ::tools_msgs::ConeArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cones == rhs.cones &&
    lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tools_msgs::ConeArray_<ContainerAllocator1> & lhs, const ::tools_msgs::ConeArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tools_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tools_msgs::ConeArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tools_msgs::ConeArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_msgs::ConeArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_msgs::ConeArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_msgs::ConeArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_msgs::ConeArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tools_msgs::ConeArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7697d41144d052204948f84dffaca26a";
  }

  static const char* value(const ::tools_msgs::ConeArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7697d41144d05220ULL;
  static const uint64_t static_value2 = 0x4948f84dffaca26aULL;
};

template<class ContainerAllocator>
struct DataType< ::tools_msgs::ConeArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tools_msgs/ConeArray";
  }

  static const char* value(const ::tools_msgs::ConeArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tools_msgs::ConeArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header                 # 时间戳+坐标系\n"
"tools_msgs/ConeInfo[] cones              # 锥桶数组\n"
"int32 count\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tools_msgs/ConeInfo\n"
"int32 cone_id\n"
"int32 color\n"
"float32 position_x\n"
"float32 position_y\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::tools_msgs::ConeArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tools_msgs::ConeArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cones);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tools_msgs::ConeArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tools_msgs::ConeArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cones: ";
    if (v.cones.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.cones.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::tools_msgs::ConeInfo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.cones[i]);
    }
    if (v.cones.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOOLS_MSGS_MESSAGE_CONEARRAY_H
