// Generated by gencpp from file tools_msgs/ConeDetection2DArray.msg
// DO NOT EDIT!


#ifndef TOOLS_MSGS_MESSAGE_CONEDETECTION2DARRAY_H
#define TOOLS_MSGS_MESSAGE_CONEDETECTION2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tools_msgs/ConeDetection2D.h>

namespace tools_msgs
{
template <class ContainerAllocator>
struct ConeDetection2DArray_
{
  typedef ConeDetection2DArray_<ContainerAllocator> Type;

  ConeDetection2DArray_()
    : header()
    , cones()  {
    }
  ConeDetection2DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cones(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tools_msgs::ConeDetection2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tools_msgs::ConeDetection2D_<ContainerAllocator> >> _cones_type;
  _cones_type cones;





  typedef boost::shared_ptr< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct ConeDetection2DArray_

typedef ::tools_msgs::ConeDetection2DArray_<std::allocator<void> > ConeDetection2DArray;

typedef boost::shared_ptr< ::tools_msgs::ConeDetection2DArray > ConeDetection2DArrayPtr;
typedef boost::shared_ptr< ::tools_msgs::ConeDetection2DArray const> ConeDetection2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator1> & lhs, const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cones == rhs.cones;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator1> & lhs, const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tools_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "744c29900cdc6759a0a8197665c4f5b3";
  }

  static const char* value(const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x744c29900cdc6759ULL;
  static const uint64_t static_value2 = 0xa0a8197665c4f5b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tools_msgs/ConeDetection2DArray";
  }

  static const char* value(const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 一帧图像中所有锥桶的2D检测结果\n"
"Header header\n"
"ConeDetection2D[] cones\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tools_msgs/ConeDetection2D\n"
"# 单个锥桶的2D检测结果\n"
"float32 x1          # 检测框左上角 x \n"
"float32 y1          # 检测框左上角 y \n"
"float32 x2          # 检测框右下角 x \n"
"float32 y2          # 检测框右下角 y \n"
"float32 confidence  # 置信度\n"
"string color        # red_cone / blue_cone / yellow_cone\n"
;
  }

  static const char* value(const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeDetection2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tools_msgs::ConeDetection2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tools_msgs::ConeDetection2DArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cones: ";
    if (v.cones.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.cones.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::tools_msgs::ConeDetection2D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.cones[i]);
    }
    if (v.cones.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOOLS_MSGS_MESSAGE_CONEDETECTION2DARRAY_H
