// Generated by gencpp from file loc_map_team/ConeStamped.msg
// DO NOT EDIT!


#ifndef LOC_MAP_TEAM_MESSAGE_CONESTAMPED_H
#define LOC_MAP_TEAM_MESSAGE_CONESTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace loc_map_team
{
template <class ContainerAllocator>
struct ConeStamped_
{
  typedef ConeStamped_<ContainerAllocator> Type;

  ConeStamped_()
    : header()
    , pos()  {
    }
  ConeStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::loc_map_team::ConeStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_map_team::ConeStamped_<ContainerAllocator> const> ConstPtr;

}; // struct ConeStamped_

typedef ::loc_map_team::ConeStamped_<std::allocator<void> > ConeStamped;

typedef boost::shared_ptr< ::loc_map_team::ConeStamped > ConeStampedPtr;
typedef boost::shared_ptr< ::loc_map_team::ConeStamped const> ConeStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_map_team::ConeStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_map_team::ConeStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::loc_map_team::ConeStamped_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::loc_map_team::ConeStamped_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace loc_map_team

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_map_team::ConeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97391420736e10df89784b25106efdf5";
  }

  static const char* value(const ::loc_map_team::ConeStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97391420736e10dfULL;
  static const uint64_t static_value2 = 0x89784b25106efdf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_map_team::ConeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_map_team/ConeStamped";
  }

  static const char* value(const ::loc_map_team::ConeStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_map_team::ConeStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point pos\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::loc_map_team::ConeStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_map_team::ConeStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_map_team::ConeStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_map_team::ConeStamped_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MAP_TEAM_MESSAGE_CONESTAMPED_H
