// Generated by gencpp from file loc_map_team/ConeArray.msg
// DO NOT EDIT!


#ifndef LOC_MAP_TEAM_MESSAGE_CONEARRAY_H
#define LOC_MAP_TEAM_MESSAGE_CONEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <loc_map_team/ConeInfo.h>

namespace loc_map_team
{
template <class ContainerAllocator>
struct ConeArray_
{
  typedef ConeArray_<ContainerAllocator> Type;

  ConeArray_()
    : header()
    , cones()  {
    }
  ConeArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cones(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::loc_map_team::ConeInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::loc_map_team::ConeInfo_<ContainerAllocator> >> _cones_type;
  _cones_type cones;





  typedef boost::shared_ptr< ::loc_map_team::ConeArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_map_team::ConeArray_<ContainerAllocator> const> ConstPtr;

}; // struct ConeArray_

typedef ::loc_map_team::ConeArray_<std::allocator<void> > ConeArray;

typedef boost::shared_ptr< ::loc_map_team::ConeArray > ConeArrayPtr;
typedef boost::shared_ptr< ::loc_map_team::ConeArray const> ConeArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_map_team::ConeArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_map_team::ConeArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::loc_map_team::ConeArray_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cones == rhs.cones;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::loc_map_team::ConeArray_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace loc_map_team

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_map_team::ConeArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fab41d45f681cfec2c7846067c21229a";
  }

  static const char* value(const ::loc_map_team::ConeArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfab41d45f681cfecULL;
  static const uint64_t static_value2 = 0x2c7846067c21229aULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_map_team::ConeArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_map_team/ConeArray";
  }

  static const char* value(const ::loc_map_team::ConeArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_map_team::ConeArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header                 # 时间戳+坐标系\n"
"ConeInfo[] cones              # 锥桶数组\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: loc_map_team/ConeInfo\n"
"geometry_msgs/Point position\n"
"string color\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::loc_map_team::ConeArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_map_team::ConeArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_map_team::ConeArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_map_team::ConeArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cones: ";
    if (v.cones.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.cones.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::loc_map_team::ConeInfo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.cones[i]);
    }
    if (v.cones.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MAP_TEAM_MESSAGE_CONEARRAY_H
