// Generated by gencpp from file loc_map_team/ConeInfo.msg
// DO NOT EDIT!


#ifndef LOC_MAP_TEAM_MESSAGE_CONEINFO_H
#define LOC_MAP_TEAM_MESSAGE_CONEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace loc_map_team
{
template <class ContainerAllocator>
struct ConeInfo_
{
  typedef ConeInfo_<ContainerAllocator> Type;

  ConeInfo_()
    : position()
    , color()  {
    }
  ConeInfo_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::loc_map_team::ConeInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_map_team::ConeInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ConeInfo_

typedef ::loc_map_team::ConeInfo_<std::allocator<void> > ConeInfo;

typedef boost::shared_ptr< ::loc_map_team::ConeInfo > ConeInfoPtr;
typedef boost::shared_ptr< ::loc_map_team::ConeInfo const> ConeInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_map_team::ConeInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_map_team::ConeInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::loc_map_team::ConeInfo_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeInfo_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::loc_map_team::ConeInfo_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace loc_map_team

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_map_team::ConeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb36a76f9fb2552b0d47bc7d542080a";
  }

  static const char* value(const ::loc_map_team::ConeInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb36a76f9fb2552ULL;
  static const uint64_t static_value2 = 0xb0d47bc7d542080aULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_map_team::ConeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_map_team/ConeInfo";
  }

  static const char* value(const ::loc_map_team::ConeInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_map_team::ConeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"string color\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::loc_map_team::ConeInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_map_team::ConeInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_map_team::ConeInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_map_team::ConeInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MAP_TEAM_MESSAGE_CONEINFO_H
