// Generated by gencpp from file loc_map_team/ConeDetection2D.msg
// DO NOT EDIT!


#ifndef LOC_MAP_TEAM_MESSAGE_CONEDETECTION2D_H
#define LOC_MAP_TEAM_MESSAGE_CONEDETECTION2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace loc_map_team
{
template <class ContainerAllocator>
struct ConeDetection2D_
{
  typedef ConeDetection2D_<ContainerAllocator> Type;

  ConeDetection2D_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , confidence(0.0)
    , color()  {
    }
  ConeDetection2D_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , confidence(0.0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::loc_map_team::ConeDetection2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_map_team::ConeDetection2D_<ContainerAllocator> const> ConstPtr;

}; // struct ConeDetection2D_

typedef ::loc_map_team::ConeDetection2D_<std::allocator<void> > ConeDetection2D;

typedef boost::shared_ptr< ::loc_map_team::ConeDetection2D > ConeDetection2DPtr;
typedef boost::shared_ptr< ::loc_map_team::ConeDetection2D const> ConeDetection2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_map_team::ConeDetection2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::loc_map_team::ConeDetection2D_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeDetection2D_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.confidence == rhs.confidence &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::loc_map_team::ConeDetection2D_<ContainerAllocator1> & lhs, const ::loc_map_team::ConeDetection2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace loc_map_team

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_map_team::ConeDetection2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_map_team::ConeDetection2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_map_team::ConeDetection2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09f91f151155db7dea880a9d6b53d71b";
  }

  static const char* value(const ::loc_map_team::ConeDetection2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09f91f151155db7dULL;
  static const uint64_t static_value2 = 0xea880a9d6b53d71bULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_map_team/ConeDetection2D";
  }

  static const char* value(const ::loc_map_team::ConeDetection2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 单个锥桶的2D检测结果\n"
"float32 x1          # 检测框左上角 x \n"
"float32 y1          # 检测框左上角 y \n"
"float32 x2          # 检测框右下角 x \n"
"float32 y2          # 检测框右下角 y \n"
"float32 confidence  # 置信度\n"
"string color        # red_cone / blue_cone / yellow_cone\n"
;
  }

  static const char* value(const ::loc_map_team::ConeDetection2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.confidence);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeDetection2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_map_team::ConeDetection2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_map_team::ConeDetection2D_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MAP_TEAM_MESSAGE_CONEDETECTION2D_H
